del Assets.dat
MyMiniz.exe Assets.dat + Assets/6x7font.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Down_Standing.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Down_Walk1.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Down_Walk2.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Left_Standing.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Left_Walk1.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Left_Walk2.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Right_Standing.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Right_Walk1.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Right_Walk2.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Up_Standing.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Up_Walk1.bmpx
MyMiniz.exe Assets.dat + Assets/Hero_Suit0_Up_Walk2.bmpx
MyMiniz.exe Assets.dat + Assets/lightning01.bmpx
MyMiniz.exe Assets.dat + Assets/polepig03.bmpx
MyMiniz.exe Assets.dat + Assets/Battle01.ogg
MyMiniz.exe Assets.dat + Assets/BattleIntro01.ogg
MyMiniz.exe Assets.dat + Assets/Dungeon01.ogg
MyMiniz.exe Assets.dat + Assets/Hit01.wav
MyMiniz.exe Assets.dat + Assets/MenuChoose.wav
MyMiniz.exe Assets.dat + Assets/MenuNavigate.wav
MyMiniz.exe Assets.dat + Assets/Miss01.wav
MyMiniz.exe Assets.dat + Assets/Overworld01.ogg
MyMiniz.exe Assets.dat + Assets/SplashScreen.wav
MyMiniz.exe Assets.dat + Assets/VictoryIntro.ogg
MyMiniz.exe Assets.dat + Assets/VictoryLoop.ogg
MyMiniz.exe Assets.dat + Assets/Maps/Overworld01.bmpx
MyMiniz.exe Assets.dat + Assets/Maps/Overworld01.tmx